---
# Source: falcon-sensor/templates/node_scc.yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: falcon-helm-falcon-sensor-access-role
  labels:
    app: "falcon-sensor"
    app.kubernetes.io/name: falcon-sensor
    app.kubernetes.io/instance: crowdstrike
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "container_sensor"
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: falcon-sensor-1.17.17
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
readOnlyRootFilesystem: false
requiredDropCapabilities:
defaultAddCapabilities:
allowedCapabilities:
users:
- crowdstrike-falcon-sa
groups:
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
